---
- name: install kcam services
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - kcam.service
    - kcam-tempd.service
  notify: reload systemd

- meta: flush_handlers

- name: activate kcam services
  tags:
    - kcam_service
  service:
    name: "{{ item }}"
    state: running
    enabled: true
  with_items:
    - rpi-configure-pwm@1
    - kcam
    - kcam-tempd
