---
- name: install kcam services
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - kcam.service
    - kcam-tempd.service
    - kcam-configure-pwm.service
  notify: reload systemd

- name: install kcam-configure-pwm script
  template:
    src: kcam-configure-pwm
    dest: /usr/bin/kcam-configure-pwm
    mode: 0755

- meta: flush_handlers

- name: activate kcam services
  tags:
    - kcam_service
  service:
    name: "{{ item }}"
    state: running
    enabled: true
  with_items:
    - kcam
    - kcam-tempd
    - kcam-configure-pwm
