---
- name: install iptables-persistent package
  package:
    name: iptables-persistent
    state: installed

- name: install iptables configuration
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
  notify: reload iptables
