---
- name: install influxdb packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ influxdb_packages }}"

- name: install influxdb configuration
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify: restart influxdb

- name: start influxdb service
  service:
    name: influxdb
    state: started
    enabled: true
